# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Project READ Literacy Network"
theme = "syna"
enableGitInfo = true
version = "0.17.3"

# Google Analytics tracking
googleAnalytics = ""

disableKinds = ["RSS", "taxonomies", "taxonomyTerms" ]

assetDir = "static"

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true
     

[params]
  name = "Project READ Literacy Network"
  description = "A Doorway to Literacy and Skills for Success Services in Waterloo-Wellington"
  

  [params.style]
   background = "light"

  # Theme customizations
  # Assets relative to 'static/'
  
   
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

[params.colors]
    primary = "#D22630"
    secondary = "#59CBE8"
    success = "#6D9E40"
    info = "#C0D725"
    warning = "#FFCE2E"
    danger = "#FFA326"
    light = "#FDFCF9"
    dark = "#B12629"
    rumble = "#4458BE"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/about"
  name = "About Us"
  weight = 10
  identifier = "about"
  
[[menu.main]]
  url = "/about/about-us.md"
  name = "History and Purpose"
  weight = 10
  parent = "about"
  
[[menu.main]]
  url = "/about/funders/index.md"
  name = "Our Funders"
  weight = 20
  parent = "about"
  
[[menu.main]]
  url = "/about/get-involved"
  name = "Get Involved"
  weight = 30
  parent = "about"
  
[[menu.main]]
  url = "/about/events"
  name = "Get Involved"
  weight = 40
  parent = "about"
  
[[menu.main]]
  url = "/about/contact"
  name = "Contact Us"
  weight = 50
  parent = "about"
  
[[menu.main]]
  url = "/programs-and-services"
  name = "Programs and Services"
  weight = 20
  identifier = "programs-and-serveices"

[[menu.main]]
  url = "/programs-and-services/programs-for-families"
  name = "Programs for Families"
  weight = 20
  parent = "programs-and-serveices"
  
[[menu.main]]
  url = "/tools"
  name = "Tools and Resources"
  weight = 40

[[menu.footer]]
  url = "/about/contact"
  name = "Contact Us"
  weight = 5

[[menu.footer]]
  url = "/about/events-and-awards/#prln-events"
  name = "Events"
  weight = 10

[[menu.footer]]
  url = "/about/get-involved/#board-of-directors"
  name = "Volunteer"
  weight = 20

[[menu.footer]]
  url = "/about/get-involved/#fundraising"
  name = "Fundraising"
  weight = 30

[[menu.copyright_footer]]
  url = "/sitemap.xml"
  name = "Sitemap"
  weight = 30

[[menu.social]]
  weight = 20
  name = "facebook"
  pre = "fab fa-facebook-f"
  url = "https://www.facebook.com/ProjectREADLitNetwork"

[[menu.social]]
  weight = 40
  name = "youtube"
  pre = "fab fa-youtube"
  url = "https://www.youtube.com/channel/UCXkRTQ0nz-8L2uiG9_FP5Ag"

[[menu.social]]
  weight = 50
  name = "instagram"
  pre = "fab fa-instagram"
  url = "https://www.instagram.com/projectreadlitnetwork/"

